eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
spring:
  datasource:
    url: jdbc:postgresql://3.64.178.33:8080/orders
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver
  application:
    name: orders-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always

axon:
  eventhandling:
    processors:
      product-group:
        mode: subscribing
logging:
  file:
    path: .\OrdersService